package(default_visibility = ["//visibility:public"])

load("//bazel:protos.bzl", "protos")

protos(
    name = "local_service",
    deps = [
        "//zetasql/local_service:local_service_proto",
    ],
)
